use-configs:
  - lint/opensource/copyrights
  - lint/opensource/banned_words
  - lint/allowed_includes
lint:
  clang-format:
    included:
      - \.cpp$
      - \.h$
      - \.inl$
      - \.hpp$
    excluded:
      - third_party/
      - infra/
      - scripts/

  cmake-format:
    included:
      - CMakeLists.txt$
      - \.cmake$
    excluded:
      - third_party/
      - infra/

  copyright:
    excluded:
      - third_party/
      - scripts/tests/copyright/out/
    mit_header:
      year_constraints:
        opencl: 2018
        shared: 2018
        level_zero: 2020

  ults-needed:
    component_names:
      - opencl
      - shared
      - level_zero/core
      - level_zero/experimental
      - level_zero/tools

  banned_words:
    exclude:
      - third_party/
    master:
      todo:
        exclude:
          - GUIDELINES.md

  allowed_includes:
    excluded:
      - third_party/
    header_extensions:
      - .h
      - .hpp
      - .inl
      - .builtin_kernel

  reference_projects:
    - NEO
    - IGC
    - HSD
    - GSD

  commit_message:
    signed_off:
      validate: mail
      skip_mails:
        - compute-runtime-validation@intel.com
        - ocldev@intel.com

  commit_message_subject:
    validate: true
    types:
      - feature
      - fix
      - refactor
      - documentation
      - build
      - ci
      - performance
      - test
    mapping:
      files:
        '*/l0_blackbox_runner_configs.yml':
        - ci
        'manifests/packaging_linux.yml':
        - ci
        'manifests/ci*.yml':
        - ci
        'manifests/*/ci*.yml':
        - ci
        '.lint-revision':
        - ci
        '.clang-tidy':
        - ci
        '*/.clang-tidy':
        - ci
        '*.md':
        - documentation
        'level_zero/api/driver_experimental/public/*':
        - feature
        - fix
        - refactor
        - performance
        - build
        'level_zero/include/*':
        - feature
        - fix
        - refactor
        - performance
        - build
      directory_0:
        '.github':
        - ci
      directory:
        test:
        - test
        target_unit_tests:
        - test
        target_aub_tests:
        - test
        source:
        - feature
        - fix
        - refactor
        - performance
        - build
      manifest:
        infra:
        - ci
        i915_kmd:
        - ci
        xe_kmd:
        - ci
        ze_raytracing:
        - ci
        aub_configs:
        - test
        kernels_bin:
        - feature
        - fix
        - build
        - performance
        _default:
        - build
    strict:
    - feature
    priority:
      0:
      - test
      - documentation
      1:
      - ci
    scope:
      values:
        - usm
        - ulls
        - ooos
        - debugger
        - zebin
        - sysman
        - ocl
        - wa
        - internal
        - ocloc
    mandatory_tracker:
      types:
        - feature
      scopes:
        - wa

